#!/bin/bash

set -u

# Use 1password to automatically connect to VPN
USER="romeli@staff-net.ethz.ch"
echo $USER
PASSWORD=$(op item get "ETHZ VPN" --fields label=password --reveal)
OTP=$(op item get "ETHZ" --otp)

echo -e ${PASSWORD}"\n"${OTP} | sudo openconnect --passwd-on-stdin --user=${USER} -g staff-net --useragent AnyConnect --no-xmlpost sslvpn.ethz.ch/staff-net
