dev:
  compiler: ['gcc']
  unify: true
  mpi: null
  specs:
  - cmake
  - ninja
  - neovim
  - python@3.11
  - py-uv
  - py-black
  - py-isort
  - py-mypy
  - py-flake8
  - py-ruff
  - py-cmake-format
  - py-fprettify
  - libtree
  - llvm targets=aarch64 ~gold ~libomptarget
  - bat
  - ruby
  - direnv
  - fd
  - go
  - lazygit
  - node-js
  - npm
  - ccache
  - ripgrep
  - tree-sitter
  - nnn
  - tmux
  - fzf
  - curl
  - gmake
  packages:
  - libtool
  - curl
  - gmake
  - perl
  - git
  variants:
    - build_type=Release
  views:
    default:
      link: roots
